### ISSUE TITLE
Hardware mounts for other headsets

### ISSUE THREAD

**Issue by RedHawk989** [RedHawk989/EyeTrackVR#10]
Create hardware mounts for other headsets like the Index, Vive Pro, HP Reverb G2 etc. Help would be appreciated if you have a unsupported headset.

**Comment by qdot** [comment]
Alpha versions of Valve Index mounts are now available in https://github.com/RedHawk989/EyeTrackVR-Hardware

**Comment by RedHawk989** [comment]
tbh feel like this issue is misplaced here. closing.
