### ISSUE TITLE
USB Cameras with similar VID/PID can collide

### ISSUE THREAD

**Issue by qdot** [RedHawk989/EyeTrackVR#30]
Trying to hook 2 wired OV5640 cameras to the same USB bus causes collision issues. The cameras can be seen by the host machine, but any effort to stream video from both at the same time ends up in only the first one connected receiving any frames. This may be an issue with how UVC is processed in OpenCV.

**Comment by RedHawk989** [comment]
Closing as we mostly moved away from wired cams for now. I don't think there is much we can do and it's not really a focus for now. Feel free to re open if anything develops.

**Comment by qdot** [comment]
No movement on this end, and if you're moving to wireless then hopefully this will cease to be an issue. :)
