### ISSUE TITLE
 Connection to tcp://192.168.4.1:80 failed: Error number -138 occurred

### ISSUE THREAD

**Issue by wukie-wq** [RedHawk989/EyeTrackVR#82]
Connection to tcp://192.168.4.1:80 failed: Error number -138 occurred

**Comment by RedHawk989** [comment]
This means the IP is incorrect, the tracker is off, or the stream is open somewhere else.

**Comment by RedHawk989** [comment]
I'm going to close this issue as it has gone stale. Re-open it if you need futher help.
